### ISSUE TITLE
pdns.cloyne isn't being loaded

### ISSUE THREAD

**Issue by clonm** [cloyne/docker-powerdns#2]
Manually changing/adding the lines from pdns.cloyne and then restarting the service was necessary to make the secondary successfully update from the primary. Future work is to automate this.

**Comment by mitar** [comment]
I fixed this with 86b22781c59c077d0d53619bde0eb8ac3f1dde01. The problem was that the filename was not loaded properly. This also means that the [workaround mentioned here](https://github.com/cloyne/docker-powerdns-primary/commit/7b37ee2f00387a756f446190ea4b2ede7eee3c72) is not good, because it configures only the bind backend, but not also the replication to ns2.cloyne.net (another DNS server, at server1). So Cloyne has been operating only with one DNS server for a long time now.
